# fly.toml app configuration file generated for http-status-codes on 2025-09-26T06:20:14-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'http-status-codes'
primary_region = "sjc"
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]
  dockerfile = "Dockerfile"

[env]
  GIN_MODE = 'release'
  PORT = '8080'

[[services]]
  protocol = 'tcp'
  internal_port = 8080
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 10000
    soft_limit = 10000
